/**
 * Branscombe Estate — 37-unit residential development
 * Source: Unison architectural drawing 20E92-03 (RevC, 2021),
 *         block "20E92-03 - proposed site plan"
 *         Planning permit PLN-21-408.02 (Glenorchy City Council).
 *
 * Site: 122-124 Branscombe Road, Claremont TAS 7011
 * 37 single-storey 3-bed / 2-bath homes by Unison, 7 Star Energy rated.
 *
 * Polygons (per-home footprints, site boundary, roads, kerbs, decks, POS) live
 * in ./polygons.json — generated by scripts/branscombe-extract/04_extract_polygons.py
 * from the Unison DWG. Coordinates in SVG-space, Y-down, viewBox 0 0 1000 ~917.
 *
 * GeoJSON (./geojson.json) — pending. Requires cadastral two-point fit before
 * Mapbox satellite overlay can render correctly.
 */

export type HouseType = "1A" | "1B" | "2A" | "2B" | "2C";

export interface UnitData {
  /** Unit identifier — "U1" through "U37". */
  id: string;
  /** Numeric unit (1..37). */
  unitNumber: number;
  /** Unison house type group. */
  type: HouseType;
  /** Geographic zone within the site (informational). */
  zone: string;
}

function unit(n: number, type: HouseType, zone: string): UnitData {
  return { id: `U${n}`, unitNumber: n, type, zone };
}

/**
 * All 37 units, ordered by unit number.
 * Type assignment per Unison architectural set (matches floor plans
 * Type 1A/1B = 104m² home, Type 2A/2B/2C = 114m² home, all + 24m² deck).
 */
export const UNITS: UnitData[] = [
  unit(1,  "1A", "SW Entry"),
  unit(2,  "1B", "SW Entry"),
  unit(3,  "1A", "SW Mid"),
  unit(4,  "2A", "SW Mid"),
  unit(5,  "2B", "SW Entry"),
  unit(6,  "2C", "SW Entry"),
  unit(7,  "1B", "Mid West"),
  unit(8,  "2A", "Mid West"),
  unit(9,  "1A", "Mid West"),
  unit(10, "2B", "North Mid"),
  unit(11, "1A", "North West"),
  unit(12, "1B", "North West"),
  unit(13, "2A", "North"),
  unit(14, "1A", "North"),
  unit(15, "2B", "North"),
  unit(16, "2C", "North"),
  unit(17, "1B", "North Mid"),
  unit(18, "2A", "NE"),
  unit(19, "1A", "NE Mid"),
  unit(20, "2B", "NE"),
  unit(21, "2C", "East Mid"),
  unit(22, "1A", "East"),
  unit(23, "1B", "East Mid"),
  unit(24, "2A", "SE Mid"),
  unit(25, "2B", "SE Mid"),
  unit(26, "2C", "SE"),
  unit(27, "1A", "SE"),
  unit(28, "1B", "SE"),
  unit(29, "2A", "South"),
  unit(30, "2B", "South"),
  unit(31, "2C", "SE Corner"),
  unit(32, "1A", "SE Corner"),
  unit(33, "1B", "East Lower"),
  unit(34, "2A", "East Lower"),
  unit(35, "2B", "East Lower"),
  unit(36, "2C", "East Mid"),
  unit(37, "1A", "East"),
];

export const HOUSE_TYPE_INFO: Record<HouseType, {
  label: string;
  size: string;
  /** Numeric home area in m² (sans deck). */
  homeAreaM2: number;
  /** Numeric deck area in m². */
  deckAreaM2: number;
  /** Pre-formatted deck string for display ("24m² deck"). */
  deck: string;
  beds: number;
  baths: number;
  /** Display colour for the home footprint on the plan view. */
  color: string;
  /** Outline colour for the home footprint. */
  border: string;
}> = {
  "1A": { label: "Type 1A", size: "104m²", homeAreaM2: 104, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#00B5AD", border: "#007F78" },
  "1B": { label: "Type 1B", size: "104m²", homeAreaM2: 104, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#0097A7", border: "#005F66" },
  "2A": { label: "Type 2A", size: "114m²", homeAreaM2: 114, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#7B1FA2", border: "#4A0F60" },
  "2B": { label: "Type 2B", size: "114m²", homeAreaM2: 114, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#512DA8", border: "#311B66" },
  "2C": { label: "Type 2C", size: "114m²", homeAreaM2: 114, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#303F9F", border: "#1B2563" },
};

/**
 * Notional land area per unit (m²), keyed by unit number.
 * Source: Branscombe_Unit_Schedule.xlsx → "Unit Schedule" sheet, "Notional land
 * (m²)" column (DA Branscombe Modular GFA Foundation Model, 23 Dec 2025).
 * Per-unit apportioned land — not a surveyed lot boundary (these are strata-style
 * dwellings on a single title). Imported 2026-06-05.
 */
export const NOTIONAL_LAND_M2: Record<number, number> = {
  1: 550, 2: 545, 3: 545, 4: 535, 5: 540, 6: 535, 7: 510, 8: 510, 9: 515,
  10: 510, 11: 520, 12: 490, 13: 485, 14: 455, 15: 480, 16: 450, 17: 480,
  18: 450, 19: 480, 20: 450, 21: 480, 22: 445, 23: 495, 24: 455, 25: 500,
  26: 460, 27: 495, 28: 460, 29: 505, 30: 510, 31: 375, 32: 350, 33: 405,
  34: 350, 35: 370, 36: 385, 37: 410,
};

/** Convenience lookup: unit id -> UnitData. */
export const UNIT_BY_ID: Record<string, UnitData> = Object.fromEntries(
  UNITS.map((u) => [u.id, u]),
);

/** All home types in display order. */
export const HOUSE_TYPES: HouseType[] = ["1A", "1B", "2A", "2B", "2C"];
